// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YksKoclukSistemi.Data;

#nullable disable

namespace YksKoclukSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260104204218_ipek")]
    partial class ipek
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YksKoclukSistemi.Models.DenemeSonuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AytNet")
                        .HasColumnType("float");

                    b.Property<string>("DenemeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<double>("TytNet")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.ToTable("DenemeSonuc");
                });

            modelBuilder.Entity("YksKoclukSistemi.Models.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dersler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "TYT Matematik"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "AYT Matematik"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Geometri"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Fizik"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Kimya"
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Biyoloji"
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Türkçe"
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Tarih"
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Coğrafya"
                        });
                });

            modelBuilder.Entity("YksKoclukSistemi.Models.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DersId")
                        .HasColumnType("int");

                    b.Property<string>("Gun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HaftalikProgramId")
                        .HasColumnType("int");

                    b.Property<bool>("YapildiMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("HaftalikProgramId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("YksKoclukSistemi.Models.HaftalikProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HaftaNumarasi")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.ToTable("HaftalikProgramlar");
                });

            modelBuilder.Entity("YksKoclukSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KocId")
                        .HasColumnType("int");

                    b.Property<int?>("Kontenjan")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KocId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("YksKoclukSistemi.Models.DenemeSonuc", b =>
                {
                    b.HasOne("YksKoclukSistemi.Models.Kullanici", "Ogrenci")
                        .WithMany("DenemeSonuclari")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("YksKoclukSistemi.Models.Gorev", b =>
                {
                    b.HasOne("YksKoclukSistemi.Models.Ders", "Ders")
                        .WithMany("Gorevler")
                        .HasForeignKey("DersId");

                    b.HasOne("YksKoclukSistemi.Models.HaftalikProgram", "HaftalikProgram")
                        .WithMany("Gorevler")
                        .HasForeignKey("HaftalikProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("HaftalikProgram");
                });

            modelBuilder.Entity("YksKoclukSistemi.Models.HaftalikProgram", b =>
                {
                    b.HasOne("YksKoclukSistemi.Models.Kullanici", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("YksKoclukSistemi.Models.Kullanici", b =>
                {
                    b.HasOne("YksKoclukSistemi.Models.Kullanici", "Koc")
                        .WithMany("Ogrencilerim")
                        .HasForeignKey("KocId");

                    b.Navigation("Koc");
                });

            modelBuilder.Entity("YksKoclukSistemi.Models.Ders", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("YksKoclukSistemi.Models.HaftalikProgram", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("YksKoclukSistemi.Models.Kullanici", b =>
                {
                    b.Navigation("DenemeSonuclari");

                    b.Navigation("Ogrencilerim");
                });
#pragma warning restore 612, 618
        }
    }
}
